---
title: "Preliminary Aspect Results, December 2020"
output: github_document
---


# Code and data preparation
```{R, load-packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lme4)
library(lmerTest)
library(emmeans)
library(sjPlot)
library(kableExtra)

options(scipen = 99)
```

```{R, load-files}
L2_EPT = read_csv("../CSV Files/L2 Learners/EPT Preterit Standardized L2 Data.csv")
L2_FCT = read_csv("../CSV Files/L2 Learners/FCT Preterit Standardized L2 Data.csv")
Heritage_EPT = read_csv("../CSV Files/Heritage/EPT Preterit Standardized Heritage Data.csv")
Heritage_FCT = read_csv("../CSV Files/Heritage/FCT Preterit Standardized Heritage Data.csv")
Comparison_EPT = read.csv("../CSV Files/Comparison/EPT Preterit Standardized Comparison Data.csv")
Comparison_FCT = read.csv("../CSV Files/Comparison/FCT Preterit Standardized Comparison Data.csv")
```

```{R, merge-datasets}
Aggregate_EPT = rbind(Comparison_EPT,L2_EPT,Heritage_EPT)
Aggregate_FCT = rbind(Comparison_EPT,L2_EPT,Heritage_EPT)
```


# Descriptive statistics
## Participant stats
```{R, participant-statistics}
Age = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(Age), na.rm = T, SD = sd(Age, na.rm = T), max(Age), min(Age))

Spanish_Acquisition = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(AoA_SPA), na.rm = T, SD = sd(AoA_SPA, na.rm = T), max(AoA_SPA), min(AoA_SPA))

English_Acquisition = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(AoA_ENG), na.rm = T, SD = sd(AoA_ENG, na.rm = T), max(AoA_ENG), min(AoA_ENG))

LOR = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(LOR), na.rm = T, SD = sd(LOR, na.rm = T), max(LOR), min(LOR))


SelfProf = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(SelfProf), na.rm = T, SD = sd(SelfProf, na.rm = T), max(SelfProf), min(SelfProf))


SelfDom = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(SelfDom), na.rm = T, SD = sd(SelfDom, na.rm = T), max(SelfDom), min(SelfDom))

DELE = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(DELE), na.rm = T, SD = sd(DELE, na.rm = T), max(DELE), min(DELE))

FofA = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(FofA), na.rm = T, SD = sd(FofA, na.rm = T), max(FofA), min(FofA))
```

## Plots of descriptive statistics
```{R, EPT-plot}
Aggregate_EPT %>%
  ggplot(aes(x = Condition, y = Average, color = ExpGroup)) + 
  facet_grid(. ~ ExpGroup) + 
  geom_hline(yintercept = 0.5, color = 'white', size = 2) + 
  stat_summary(fun = mean,
               geom = 'pointrange', size = 1, 
               position = position_dodge(width = 0.5)) + 
  scale_color_brewer(palette = "Set1", name = "") +
  theme(legend.position = "none") +
  ylim(c(0,1)) +
  labs(x = 'Condition', y = 'Proportion of expected responses', caption = '', 
       title = 'Descriptive Statistics by Condition, Production Task')
```

```{R, FCT-plot}
Aggregate_FCT %>%
  ggplot(aes(x = Condition, y = Average, color = ExpGroup)) + 
  facet_grid(. ~ ExpGroup) + 
  geom_hline(yintercept = 0.5, color = 'white', size = 2) + 
  stat_summary(fun = mean,
               geom = 'pointrange', size = 1, 
               position = position_dodge(width = 0.5)) + 
  scale_color_brewer(palette = "Set1", name = "") +
  theme(legend.position = "none") +
  ylim(c(0,1)) +
  labs(x = 'Condition', y = 'Proportion of expected responses', caption = '', 
       title = 'Descriptive Statistics by Condition, FCT')
```


# Models for Heritage Speakers
* **Dependent variable:** Suppliance of Preterit in subordinate clause
* **Independent variables (continuous):** Token frequency of matrix verb (Type_Std), DELE score (DELE_Std), frequency of use of Spanish (FofA_Std)
* **Independent variable (categorical):** Type frequency of preterit morphology (0 = irregular, 1 = regular; Type_Main)

## Production data for HS
```{R, run-HS-production}
HS_Production_Model = lmer(
  Average ~ FofA_Std + Token_Lemma_Std + Type_Main + DELE_Std + Token_Lemma_Std:Type_Main + FofA_Std:Token_Lemma_Std + FofA_Std:Type_Main + DELE_Std:Token_Lemma_Std:Type_Main + FofA_Std:Token_Lemma_Std:Type_Main +
    (1 | Participant) + (1 | Item),
  data = Heritage_EPT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(HS_Production_Model)
```
**Table 3.** Results of elicited production task for heritage speakers.

## FCT data for HS
```{R, run-HS-comprehension}
HS_FCT_Model = lmer(
  Average ~ FofA_Std + Token_Lemma_Std + Type_Main + DELE_Std + Token_Lemma_Std:Type_Main + FofA_Std:Token_Lemma_Std + FofA_Std:Type_Main + DELE_Std:Token_Lemma_Std:Type_Main + FofA_Std:Token_Lemma_Std:Type_Main +
    (1 | Participant) + (1 | Item),
  data = Heritage_FCT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(HS_FCT_Model)
```
**Table 4.** Results of FCT for heritage speakers.

## Comments/questions on HS data
1. The statistically-significant effect for frequency of use of Spanish in production, along with the three-way interaction between type frequency, token frequency, and frequency of use, support the hypotheses of the present study.
2. Oddly, there is a main effect for proficiency in the comprehension task.  This was not expected.  Why would we see that proficiency level modulates comprehension but not production?
3. It is important to recognize that the comparison group's results are far from categorical.  I still have only recruited 11 Spanish-dominant comparison participants, and so I expect to find more consistency in the results once I have more data for this group.


# Models for L2 Learners
* **Dependent variable:** Suppliance of Preterit in subordinate clause
* **Independent variables (continuous):** Token frequency of matrix verb (Type_Std), DELE score (DELE_Std), frequency of use of Spanish (FofA_Std)
* **Independent variable (categorical):** Type frequency of preterit morphology (0 = irregular, 1 = regular; Type_Main)

## Production data for L2 Learners
```{R, run-L2-production}
L2_Production_Model = lmer(
  Average ~ FofA_Std + Token_Lemma_Std + Type_Main + DELE_Std + DELE_Std:Type_Main + DELE_Std:Token_Lemma_Std + LOR_Std:Type_Main + DELE_Std:Token_Lemma_Std:Type_Main + FofA_Std:Token_Lemma_Std:Type_Main + DELE_Std:FofA_Std:Token_Lemma_Std:Type_Main +
    (1 | LOR_Std) + (1 | Item),
  data = L2_EPT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(L2_Production_Model)
```
**Table 5.** Results of elicited production task for L2 learners.

## FCT data for L2 Learners
```{R, run-L2-comprehension}
L2_FCT_Model = lmer(
  Average ~ FofA_Std + Token_Lemma_Std + Type_Main + DELE_Std + DELE_Std:Type_Main + DELE_Std:Token_Lemma_Std + LOR_Std:Type_Main + DELE_Std:Token_Lemma_Std:Type_Main + FofA_Std:Token_Lemma_Std:Type_Main + DELE_Std:FofA_Std:Token_Lemma_Std:Type_Main +
    (1 | LOR_Std) + (1 | Item),
  data = L2_FCT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(L2_FCT_Model)
```
**Table 6.** Results of FCT for L2 learners.

## Comments/questions on L2 data

1. You will notice that I didn't run participant as a random effect for the L2 learner comprehension model.  I am having difficulty operationalizing this in the model; there appears to be an issue with the code, even though the same system worked for my HS participants.
2. Interestingly, the same tendencies observed for the interaction between type and token frequency with HS is upheld for L2 learners in production, with the exception being that DELE score interacts with these variables rather than frequency of activation.