---
title: "Preliminary Subjunctive Results, December 2020"
output: github_document
---

**The results shared below show the statistical models for the heritage and L2 groups in the elicited production task (EPT) and the receptive forced choice task (FCT).  I begin with a presentation of the descriptive stats for the subjunctive items in production and comprehension.  Below the descriptive stats are the results of the linear mixed regressions that I ran for the heritage group (EPT and FCT) and the L2 learners (EPT and FCT) as well as results with the control group added (EPT and FCT).  I have listed some questions and comments below each section.  Note that I am still working on plotting the outputs of the models; I'll need to meet with Joseph to discuss this further.**

# Code and data preparation
```{R, load-packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lme4)
library(lmerTest)
library(emmeans)
library(sjPlot)
library(kableExtra)

options(scipen = 99)
```

```{R, load-files}
L2_EPT = read_csv("../CSV Files/L2 Learners/EPT Subjunctive Standardized L2 Data.csv")
L2_FCT = read_csv("../CSV Files/L2 Learners/FCT Subjunctive Standardized L2 Data.csv")
Heritage_EPT = read_csv("../CSV Files/Heritage/EPT Subjunctive Standardized Heritage Data.csv")
Heritage_FCT = read_csv("../CSV Files/Heritage/FCT Subjunctive Standardized Heritage Data.csv")
Comparison_EPT = read.csv("../CSV Files/Comparison/EPT Subjunctive Standardized Comparison Data.csv")
Comparison_FCT = read.csv("../CSV Files/Comparison/FCT Subjunctive Standardized Comparison Data.csv")
```

```{R, merge-datasets}
Aggregate_EPT = rbind(Comparison_EPT,L2_EPT,Heritage_EPT)
Aggregate_FCT = rbind(Comparison_EPT,L2_EPT,Heritage_EPT)
Aggregate_Composite = rbind(Aggregate_EPT, Aggregate_FCT)
```


# Descriptive statistics
## Participant stats
```{R, participant-statistics}
Age = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(Age), na.rm = T, SD = sd(Age, na.rm = T), max(Age), min(Age))

Spanish_Acquisition = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(AoA_SPA), na.rm = T, SD = sd(AoA_SPA, na.rm = T), max(AoA_SPA), min(AoA_SPA))

English_Acquisition = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(AoA_ENG), na.rm = T, SD = sd(AoA_ENG, na.rm = T), max(AoA_ENG), min(AoA_ENG))

LOR = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(LOR), na.rm = T, SD = sd(LOR, na.rm = T), max(LOR), min(LOR))


SelfProf = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(SelfProf), na.rm = T, SD = sd(SelfProf, na.rm = T), max(SelfProf), min(SelfProf))


SelfDom = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(SelfDom), na.rm = T, SD = sd(SelfDom, na.rm = T), max(SelfDom), min(SelfDom))

DELE = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(DELE), na.rm = T, SD = sd(DELE, na.rm = T), max(DELE), min(DELE))

FofA = Aggregate_EPT %>%
  group_by(ExpGroup) %>%
  summarize(Average = mean(FofA), na.rm = T, SD = sd(FofA, na.rm = T), max(FofA), min(FofA))
```

## Plots of descriptive statistics
```{R, EPT-plot}
Aggregate_EPT %>%
  ggplot(aes(x = Condition, y = Average, color = ExpGroup)) + 
  facet_grid(. ~ ExpGroup) + 
  geom_hline(yintercept = 0.5, color = 'white', size = 2) + 
  stat_summary(fun = mean,
               geom = 'pointrange', size = 1, 
               position = position_dodge(width = 0.5)) + 
  scale_color_brewer(palette = "Set1", name = "") +
  theme(legend.position = "none") +
  ylim(c(0,1)) +
  labs(x = 'Condition', y = 'Proportion of expected responses', caption = '', 
       title = 'Descriptive Statistics by Condition, Production Task')
```

```{R, FCT-plot}
Aggregate_FCT %>%
  ggplot(aes(x = Condition, y = Average, color = ExpGroup)) + 
  facet_grid(. ~ ExpGroup) + 
  geom_hline(yintercept = 0.5, color = 'white', size = 2) + 
  stat_summary(fun = mean,
               geom = 'pointrange', size = 1, 
               position = position_dodge(width = 0.5)) + 
  scale_color_brewer(palette = "Set1", name = "") +
  theme(legend.position = "none") +
  ylim(c(0,1)) +
  labs(x = 'Condition', y = 'Proportion of expected responses', caption = '', 
       title = 'Descriptive Statistics by Condition, FCT')
```


# Models for Heritage Speakers
* **Dependent variable (binary):** Suppliance of subjunctive in subordinate clause
* **Independent variables (continuous):** Token frequency of matrix verb (Token_Main_Std), DELE score (DELE_Std_), frequency of use of Spanish (FofA_Std)

## Production data for HS
```{R, run-HS-production}
HS_Production_Model = lmer(
  Average ~ FofA_Std + Token_Main_Std + DELE_Std + FofA_Std + Token_Main_Std + DELE_Std:Token_Main_Std + FofA_Std:Token_Main_Std +
    (1 | Participant) + (1 | Item),
  data = Heritage_EPT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(HS_Production_Model)
```
**Table 3.** Results of elicited production task for heritage speakers.

## FCT data for HS
```{R, run-HS-comprehension}
HS_FCT_Model = lmer(
  Average ~ FofA_Std + Token_Main_Std + DELE_Std + FofA_Std + Token_Main_Std + DELE_Std:Token_Main_Std + FofA_Std:Token_Main_Std +
    (1 | Participant) + (1 | Item),
  data = Heritage_FCT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(HS_FCT_Model)
```
**Table 4.** Results of FCT for heritage speakers.

## Comments/questions on HS data

1. Should I bother reporting the DELE data?  It appears statistically significant but it's not novel, and if anything, it weakens my argument that patterns of activation are influential.

2. Last I checked about one week ago, the *p* value for the interaction between frequency of use and token frequency was .0023 off from significant in production.

3. It appears that the interaction that I described in #2 is moderately significant in comprehension, which is surprising, considering we would expect differences to emerge more visibly in the realm of production.

# Models for L2 Learners
* **Dependent variable:** Suppliance of subjunctive in subordinate clause
* **Independent variables (continuous):** Token frequency of matrix verb (Token_Main_Std), DELE score (DELE_Std_), frequency of use of Spanish (FofA_Std)

## Production data for L2 Learners
```{R, run-L2-production}
L2_Production_Model = lmer(
  Average ~ FofA_Std + Token_Main_Std + DELE_Std + FofA_Std + DELE_Std:Token_Main_Std + FofA_Std:Token_Main_Std + DELE_Std:FofA_Std:Token_Main_Std +
    (1 | LOR_Std) + (1 | Item),
  data = L2_EPT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(L2_Production_Model)
```
**Table 5.** Results of elicited production task for L2 learners.

## FCT data for L2 Learners
```{R, run-L2-comprehension}
L2_FCT_Model = lmer(
  Average ~ FofA_Std + Token_Main_Std + DELE_Std + FofA_Std + DELE_Std:Token_Main_Std + FofA_Std:Token_Main_Std + DELE_Std:FofA_Std:Token_Main_Std +
   (1 | LOR_Std) + (1 | Item),
  data = L2_FCT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(L2_FCT_Model)
```
**Table 6.** Results of FCT for L2 learners.

## Comments/questions on L2 data

1. You will notice that I didn't run participant as a random effect for the L2 learner comprehension model.  I am having difficulty operationalizing this variable; there appears to be an issue with the code, even though the same system worked for my HS participants.

# Subjunctive data with all groups
* **Dependent variable:** Suppliance of subjunctive in subordinate clause
* **Independent variables (continuous):** Token frequency of matrix verb (Token_Main_Std), DELE score (DELE_Std), frequency of use of Spanish (FofA_Std)
* **Independent variable (categorical):** Experimental group (ExpGroup)

## Production results by group
```{R, by-group-analysis-production}
ByGroup_Production_Model = lmer(
  Average ~ ExpGroup + FofA_Std + Token_Main_Std + DELE_Std + FofA_Std + ExpGroup:FofA_Std + ExpGroup:Token_Main_Std + ExpGroup:DELE_Std + ExpGroup:DELE_Std:FofA_Std + ExpGroup:DELE_Std:Token_Main_Std + ExpGroup:FofA_Std:Token_Main_Std +
    (1 | LOR_Std) + (1 | Participant) + (1 | Item),
  data = Aggregate_EPT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(ByGroup_Production_Model)
```
**Table 7.** Results for production task with group as a categorical variable

## Comprehension results by group
```{R, by-group-analysis-comprehension}
ByGroup_FCT_Model = lmer(
  Average ~ ExpGroup + FofA_Std + Token_Main_Std + DELE_Std + FofA_Std + ExpGroup:FofA_Std + ExpGroup:Token_Main_Std + ExpGroup:DELE_Std + ExpGroup:DELE_Std:FofA_Std + ExpGroup:DELE_Std:Token_Main_Std + ExpGroup:FofA_Std:Token_Main_Std +
    (1 | LOR_Std) + (1 | Participant) + (1 | Item),
  data = Aggregate_FCT,
  control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun=3e5)))

tab_model(ByGroup_FCT_Model)
```
**Table 8.** Results for FCT with group as a categorical variable.

## Comments
1. It seems the L2 data is a lot "cleaner" than the heritage data, but I suppose this is to be expected.  There is probably less heterogeneity across proficiency levels in the instructed learner population than there is in the HS population.

2. I was hoping to see an interaction between token frequency and frequency of activation for both bilingual groups in the production task, but it seems as if the results are about .01 off from statistically significant.

3. In general, I think I have found fewer intermediate HS, and perhaps I will need to try to recruit 4-5 more from the introductory courses at Rutgers at the start of next semester.  Again, the results are near significant, and with the continuous variables of my study, it is logical that I need a larger sample size in order for the models to pick up on trends.